workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_connect
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bookmylook.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.bookmylook.app"
      node: 20
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
          echo "=== Checking node_modules ==="
          ls -la node_modules/@capacitor/ios/ || echo "Capacitor iOS not found"
      - name: Check iOS folder structure
        script: |
          echo "=== Checking iOS folder structure ==="
          ls -la ios/
          ls -la ios/App/
          cat ios/App/Podfile
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install --repo-update
      - name: Initialize keychain
        script: |
          keychain initialize
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Set build version
        script: |
          cd ios/App
          agvtool new-version -all 73
          agvtool new-marketing-version 2.8.3
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - listenrayees@gmail.com
        notify:
          success: true
          failure: true