workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_connect
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bookmylook.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.bookmylook.app"
      node: 20
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Initialize keychain
        script: |
          keychain initialize
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Set build version
        script: |
          cd ios/App
          agvtool new-version -all 62
          agvtool new-marketing-version 2.7.4
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - listenrayees@gmail.com
        notify:
          success: true
          failure: true

  android-production:
    name: Android Production Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      groups:
        - keystore_credentials
      vars:
        KEYSTORE_PATH: android/bookmylook-new.keystore
      node: 20
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor Android
        script: |
          npx cap sync android
      - name: Set Android version
        script: |
          cd android
          sed -i 's/versionCode [0-9]*/versionCode 62/' app/build.gradle
          sed -i 's/versionName "[^"]*"/versionName "2.7.4"/' app/build.gradle
      - name: Build Android AAB
        script: |
          cd android
          ./gradlew bundleRelease
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - listenrayees@gmail.com
        notify:
          success: true
          failure: true