workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_connect
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bookmylook.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Set build version
        script: |
          cd ios/App
          agvtool new-version -all 63
          agvtool new-marketing-version 2.7.4
      - name: Install Capacitor dependencies
        script: |
          npm install @capacitor/ios @capacitor/core capacitor-razorpay
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - listenrayees@gmail.com
        notify:
          success: true
          failure: true